/**
 * Standard complete inventory list for Annpurna Mess
 * Total items: 135
 */
export const DEFAULT_INVENTORY = [
  { item: 'Toor Dal (Pigeon Peas)', item_name: 'Toor Dal (Pigeon Peas)', qty: 750, quantity: 750, unit: 'g', category: 'Pulses & Dals', minThreshold: 100 },
  { item: 'Masoor Dal (Red Lentils)', item_name: 'Masoor Dal (Red Lentils)', qty: 750, quantity: 750, unit: 'g', category: 'Pulses & Dals', minThreshold: 100 },
  { item: 'Cooking Oil', item_name: 'Cooking Oil', qty: 5, quantity: 5, unit: 'L', category: 'Oils & Ghee', minThreshold: 2 },
  { item: 'Peanuts / Groundnuts', item_name: 'Peanuts / Groundnuts', qty: 2, quantity: 2, unit: 'kg', category: 'Dry Fruits & Nuts', minThreshold: 1 },
  { item: 'Poha (Flattened Rice)', item_name: 'Poha (Flattened Rice)', qty: 2, quantity: 2, unit: 'kg', category: 'Grains & Flours', minThreshold: 1 },
  { item: 'Matki Masala', item_name: 'Matki Masala', qty: 200, quantity: 200, unit: 'g', category: 'Spices & Masalas', minThreshold: 50 },
  { item: 'Sugar', item_name: 'Sugar', qty: 0, quantity: 0, unit: 'kg', category: 'Essentials', minThreshold: 10 },
  { item: 'Rice', item_name: 'Rice', qty: 0, quantity: 0, unit: 'kg', category: 'Grains & Flours', minThreshold: 20 },
  { item: 'Urad Dal (Black Gram)', item_name: 'Urad Dal (Black Gram)', qty: 0, quantity: 0, unit: 'kg', category: 'Pulses & Dals', minThreshold: 5 },
  { item: 'Moong Dal (Yellow Lentils)', item_name: 'Moong Dal (Yellow Lentils)', qty: 0, quantity: 0, unit: 'kg', category: 'Pulses & Dals', minThreshold: 5 },
  { item: 'Chana Dal (Split Chickpeas)', item_name: 'Chana Dal (Split Chickpeas)', qty: 0, quantity: 0, unit: 'kg', category: 'Pulses & Dals', minThreshold: 5 },
  { item: 'Moth Dal (Turkish Gram)', item_name: 'Moth Dal (Turkish Gram)', qty: 0, quantity: 0, unit: 'kg', category: 'Pulses & Dals', minThreshold: 5 },
  { item: 'Dalda / Vanaspati Ghee', item_name: 'Dalda / Vanaspati Ghee', qty: 0, quantity: 0, unit: 'kg', category: 'Oils & Ghee', minThreshold: 5 },
  { item: 'Besan (Gram Flour)', item_name: 'Besan (Gram Flour)', qty: 0, quantity: 0, unit: 'kg', category: 'Grains & Flours', minThreshold: 10 },
  { item: 'Tata Salt', item_name: 'Tata Salt', qty: 0, quantity: 0, unit: 'kg', category: 'Essentials', minThreshold: 5 },
  { item: 'Plain Salt', item_name: 'Plain Salt', qty: 0, quantity: 0, unit: 'kg', category: 'Essentials', minThreshold: 5 },
  { item: 'Maida (All-Purpose Flour)', item_name: 'Maida (All-Purpose Flour)', qty: 0, quantity: 0, unit: 'kg', category: 'Grains & Flours', minThreshold: 10 },
  { item: 'Rava / Semolina', item_name: 'Rava / Semolina', qty: 0, quantity: 0, unit: 'kg', category: 'Grains & Flours', minThreshold: 10 },
  { item: 'Dry Coconut', item_name: 'Dry Coconut', qty: 0, quantity: 0, unit: 'kg', category: 'Dry Fruits & Nuts', minThreshold: 2 },
  { item: 'Jaggery', item_name: 'Jaggery', qty: 0, quantity: 0, unit: 'kg', category: 'Essentials', minThreshold: 5 },
  { item: 'Sabudana (Tapioca Pearls)', item_name: 'Sabudana (Tapioca Pearls)', qty: 0, quantity: 0, unit: 'kg', category: 'Grains & Flours', minThreshold: 5 },
  { item: 'Whole Moong', item_name: 'Whole Moong', qty: 0, quantity: 0, unit: 'kg', category: 'Pulses & Dals', minThreshold: 5 },
  { item: 'Matki (Moth Beans)', item_name: 'Matki (Moth Beans)', qty: 0, quantity: 0, unit: 'kg', category: 'Pulses & Dals', minThreshold: 5 },
  { item: 'Dried Peas', item_name: 'Dried Peas', qty: 0, quantity: 0, unit: 'kg', category: 'Pulses & Dals', minThreshold: 5 },
  { item: 'Soya Chunks (Soya Vadi)', item_name: 'Soya Chunks (Soya Vadi)', qty: 0, quantity: 0, unit: 'kg', category: 'Pulses & Dals', minThreshold: 5 },
  { item: 'Kabuli Chana (Chickpeas)', item_name: 'Kabuli Chana (Chickpeas)', qty: 0, quantity: 0, unit: 'kg', category: 'Pulses & Dals', minThreshold: 5 },
  { item: 'Brown Chana (Kala Chana)', item_name: 'Brown Chana (Kala Chana)', qty: 0, quantity: 0, unit: 'kg', category: 'Pulses & Dals', minThreshold: 5 },
  { item: 'Cowpeas (Black-Eyed Peas)', item_name: 'Cowpeas (Black-Eyed Peas)', qty: 0, quantity: 0, unit: 'kg', category: 'Pulses & Dals', minThreshold: 5 },
  { item: 'Kidney Beans (Rajma)', item_name: 'Kidney Beans (Rajma)', qty: 0, quantity: 0, unit: 'kg', category: 'Pulses & Dals', minThreshold: 5 },
  { item: 'Bobby Fryums', item_name: 'Bobby Fryums', qty: 0, quantity: 0, unit: 'kg', category: 'Packaged & Ready Foods', minThreshold: 2 },
  { item: 'Bhagar (Barnyard Millet / Samo)', item_name: 'Bhagar (Barnyard Millet / Samo)', qty: 0, quantity: 0, unit: 'kg', category: 'Grains & Flours', minThreshold: 5 },
  { item: 'Poha Chura / Puffed Flakes', item_name: 'Poha Chura / Puffed Flakes', qty: 0, quantity: 0, unit: 'kg', category: 'Grains & Flours', minThreshold: 5 },
  { item: 'Sella Rice', item_name: 'Sella Rice', qty: 0, quantity: 0, unit: 'kg', category: 'Grains & Flours', minThreshold: 20 },
  { item: 'Pearl Millet (Bajra)', item_name: 'Pearl Millet (Bajra)', qty: 0, quantity: 0, unit: 'kg', category: 'Grains & Flours', minThreshold: 10 },
  { item: 'Sanghavi Gold Wheat Flour', item_name: 'Sanghavi Gold Wheat Flour', qty: 0, quantity: 0, unit: 'kg', category: 'Grains & Flours', minThreshold: 25 },
  { item: 'Corn Flour / Cornstarch', item_name: 'Corn Flour / Cornstarch', qty: 0, quantity: 0, unit: 'kg', category: 'Grains & Flours', minThreshold: 2 },
  { item: 'Lapsi Rava (Broken Wheat)', item_name: 'Lapsi Rava (Broken Wheat)', qty: 0, quantity: 0, unit: 'kg', category: 'Grains & Flours', minThreshold: 5 },
  { item: 'Horse Gram (Kulith)', item_name: 'Horse Gram (Kulith)', qty: 0, quantity: 0, unit: 'kg', category: 'Pulses & Dals', minThreshold: 5 },
  { item: 'Idli Rava', item_name: 'Idli Rava', qty: 0, quantity: 0, unit: 'kg', category: 'Grains & Flours', minThreshold: 5 },
  { item: 'Sorghum (Jowar)', item_name: 'Sorghum (Jowar)', qty: 0, quantity: 0, unit: 'kg', category: 'Grains & Flours', minThreshold: 10 },
  { item: 'Whole Black Urad Dal', item_name: 'Whole Black Urad Dal', qty: 0, quantity: 0, unit: 'kg', category: 'Pulses & Dals', minThreshold: 5 },
  { item: 'Split Green Moong Dal (Chilka)', item_name: 'Split Green Moong Dal (Chilka)', qty: 0, quantity: 0, unit: 'kg', category: 'Pulses & Dals', minThreshold: 5 },
  { item: 'Tea Leaves / Powder', item_name: 'Tea Leaves / Powder', qty: 0, quantity: 0, unit: 'kg', category: 'Beverages', minThreshold: 3 },
  { item: 'Sesame Seeds', item_name: 'Sesame Seeds', qty: 0, quantity: 0, unit: 'kg', category: 'Dry Fruits & Nuts', minThreshold: 1 },
  { item: 'Broken Cashews (Kaju Kani)', item_name: 'Broken Cashews (Kaju Kani)', qty: 0, quantity: 0, unit: 'kg', category: 'Dry Fruits & Nuts', minThreshold: 1 },
  { item: 'Melon Seeds (Magaz)', item_name: 'Melon Seeds (Magaz)', qty: 0, quantity: 0, unit: 'kg', category: 'Dry Fruits & Nuts', minThreshold: 1 },
  { item: 'Kohinoor Basmati Rice', item_name: 'Kohinoor Basmati Rice', qty: 0, quantity: 0, unit: 'kg', category: 'Grains & Flours', minThreshold: 20 },
  { item: 'Rock / Coarse Salt', item_name: 'Rock / Coarse Salt', qty: 0, quantity: 0, unit: 'kg', category: 'Essentials', minThreshold: 2 },
  { item: 'Tomato Sauce / Ketchup', item_name: 'Tomato Sauce / Ketchup', qty: 0, quantity: 0, unit: 'kg', category: 'Condiments & Sauces', minThreshold: 2 },
  { item: 'Sarvam Red Chilli Powder', item_name: 'Sarvam Red Chilli Powder', qty: 0, quantity: 0, unit: 'kg', category: 'Spices & Masalas', minThreshold: 2 },
  { item: 'Ambari Red Chilli Powder', item_name: 'Ambari Red Chilli Powder', qty: 0, quantity: 0, unit: 'kg', category: 'Spices & Masalas', minThreshold: 2 },
  { item: 'Turmeric Powder', item_name: 'Turmeric Powder', qty: 0, quantity: 0, unit: 'kg', category: 'Spices & Masalas', minThreshold: 2 },
  { item: 'Coriander Powder', item_name: 'Coriander Powder', qty: 0, quantity: 0, unit: 'kg', category: 'Spices & Masalas', minThreshold: 2 },
  { item: 'Cumin Seeds', item_name: 'Cumin Seeds', qty: 0, quantity: 0, unit: 'kg', category: 'Whole Spices', minThreshold: 1 },
  { item: 'Mustard Seeds', item_name: 'Mustard Seeds', qty: 0, quantity: 0, unit: 'kg', category: 'Whole Spices', minThreshold: 1 },
  { item: 'Papad', item_name: 'Papad', qty: 0, quantity: 0, unit: 'kg', category: 'Packaged & Ready Foods', minThreshold: 2 },
  { item: 'Jaljeera Powder', item_name: 'Jaljeera Powder', qty: 0, quantity: 0, unit: 'g', category: 'Spices & Masalas', minThreshold: 100 },
  { item: 'Asafoetida (Hing)', item_name: 'Asafoetida (Hing)', qty: 0, quantity: 0, unit: 'g', category: 'Spices & Masalas', minThreshold: 50 },
  { item: 'Kasuri Methi (Dried Fenugreek)', item_name: 'Kasuri Methi (Dried Fenugreek)', qty: 0, quantity: 0, unit: 'g', category: 'Spices & Masalas', minThreshold: 100 },
  { item: 'Fenugreek Seeds', item_name: 'Fenugreek Seeds', qty: 0, quantity: 0, unit: 'kg', category: 'Whole Spices', minThreshold: 1 },
  { item: 'Tamarind', item_name: 'Tamarind', qty: 0, quantity: 0, unit: 'kg', category: 'Essentials', minThreshold: 2 },
  { item: 'Baking Soda', item_name: 'Baking Soda', qty: 0, quantity: 0, unit: 'g', category: 'Baking & Cooking Aids', minThreshold: 100 },
  { item: 'Tartaric Acid / Citric Acid (Tatree)', item_name: 'Tartaric Acid / Citric Acid (Tatree)', qty: 0, quantity: 0, unit: 'g', category: 'Baking & Cooking Aids', minThreshold: 100 },
  { item: 'Everest Kitchen King Masala', item_name: 'Everest Kitchen King Masala', qty: 0, quantity: 0, unit: 'g', category: 'Spices & Masalas', minThreshold: 200 },
  { item: 'Everest Chhole Masala', item_name: 'Everest Chhole Masala', qty: 0, quantity: 0, unit: 'g', category: 'Spices & Masalas', minThreshold: 200 },
  { item: 'Everest Biryani Masala', item_name: 'Everest Biryani Masala', qty: 0, quantity: 0, unit: 'g', category: 'Spices & Masalas', minThreshold: 200 },
  { item: 'Sambar Masala', item_name: 'Sambar Masala', qty: 0, quantity: 0, unit: 'g', category: 'Spices & Masalas', minThreshold: 200 },
  { item: 'Super Garam Masala', item_name: 'Super Garam Masala', qty: 0, quantity: 0, unit: 'g', category: 'Spices & Masalas', minThreshold: 200 },
  { item: 'Goda Masala', item_name: 'Goda Masala', qty: 0, quantity: 0, unit: 'g', category: 'Spices & Masalas', minThreshold: 200 },
  { item: 'Chaat Masala', item_name: 'Chaat Masala', qty: 0, quantity: 0, unit: 'g', category: 'Spices & Masalas', minThreshold: 200 },
  { item: 'Chicken Masala', item_name: 'Chicken Masala', qty: 0, quantity: 0, unit: 'g', category: 'Spices & Masalas', minThreshold: 200 },
  { item: 'Everest Pav Bhaji Masala', item_name: 'Everest Pav Bhaji Masala', qty: 0, quantity: 0, unit: 'g', category: 'Spices & Masalas', minThreshold: 200 },
  { item: 'Rajma Masala', item_name: 'Rajma Masala', qty: 0, quantity: 0, unit: 'g', category: 'Spices & Masalas', minThreshold: 200 },
  { item: 'Dabeli Masala', item_name: 'Dabeli Masala', qty: 0, quantity: 0, unit: 'g', category: 'Spices & Masalas', minThreshold: 200 },
  { item: 'Kothmir (Coriander) Masala', item_name: 'Kothmir (Coriander) Masala', qty: 0, quantity: 0, unit: 'g', category: 'Spices & Masalas', minThreshold: 200 },
  { item: 'Sangamneri Zatka Masala', item_name: 'Sangamneri Zatka Masala', qty: 0, quantity: 0, unit: 'g', category: 'Spices & Masalas', minThreshold: 200 },
  { item: 'Kala Garam Masala', item_name: 'Kala Garam Masala', qty: 0, quantity: 0, unit: 'g', category: 'Spices & Masalas', minThreshold: 200 },
  { item: 'Kanda Lasun (Onion Garlic) Masala', item_name: 'Kanda Lasun (Onion Garlic) Masala', qty: 0, quantity: 0, unit: 'g', category: 'Spices & Masalas', minThreshold: 200 },
  { item: 'Everest Mutton Masala', item_name: 'Everest Mutton Masala', qty: 0, quantity: 0, unit: 'g', category: 'Spices & Masalas', minThreshold: 200 },
  { item: 'Sabzi Masala', item_name: 'Sabzi Masala', qty: 0, quantity: 0, unit: 'g', category: 'Spices & Masalas', minThreshold: 200 },
  { item: 'Chatpat Masala', item_name: 'Chatpat Masala', qty: 0, quantity: 0, unit: 'g', category: 'Spices & Masalas', minThreshold: 200 },
  { item: 'Green Cardamom', item_name: 'Green Cardamom', qty: 0, quantity: 0, unit: 'g', category: 'Whole Spices', minThreshold: 50 },
  { item: 'Star Anise', item_name: 'Star Anise', qty: 0, quantity: 0, unit: 'g', category: 'Whole Spices', minThreshold: 50 },
  { item: 'Black Peppercorns', item_name: 'Black Peppercorns', qty: 0, quantity: 0, unit: 'g', category: 'Whole Spices', minThreshold: 100 },
  { item: 'Cloves', item_name: 'Cloves', qty: 0, quantity: 0, unit: 'g', category: 'Whole Spices', minThreshold: 50 },
  { item: 'Cinnamon', item_name: 'Cinnamon', qty: 0, quantity: 0, unit: 'g', category: 'Whole Spices', minThreshold: 100 },
  { item: 'Mace (Jayapatri)', item_name: 'Mace (Jayapatri)', qty: 0, quantity: 0, unit: 'g', category: 'Whole Spices', minThreshold: 50 },
  { item: 'Whole Black Pepper', item_name: 'Whole Black Pepper', qty: 0, quantity: 0, unit: 'g', category: 'Whole Spices', minThreshold: 100 },
  { item: 'Poppy Seeds (Khus Khus)', item_name: 'Poppy Seeds (Khus Khus)', qty: 0, quantity: 0, unit: 'g', category: 'Whole Spices', minThreshold: 100 },
  { item: 'Stone Flower (Dagad Phool / Kalpasi)', item_name: 'Stone Flower (Dagad Phool / Kalpasi)', qty: 0, quantity: 0, unit: 'g', category: 'Whole Spices', minThreshold: 50 },
  { item: 'Black Cardamom', item_name: 'Black Cardamom', qty: 0, quantity: 0, unit: 'g', category: 'Whole Spices', minThreshold: 50 },
  { item: 'Caraway Seeds (Shahi Jeera)', item_name: 'Caraway Seeds (Shahi Jeera)', qty: 0, quantity: 0, unit: 'g', category: 'Whole Spices', minThreshold: 50 },
  { item: 'Nutmeg Blade / Rampatri', item_name: 'Nutmeg Blade / Rampatri', qty: 0, quantity: 0, unit: 'g', category: 'Whole Spices', minThreshold: 50 },
  { item: 'Bay Leaves', item_name: 'Bay Leaves', qty: 0, quantity: 0, unit: 'g', category: 'Whole Spices', minThreshold: 100 },
  { item: 'Tomato Red Food Color', item_name: 'Tomato Red Food Color', qty: 0, quantity: 0, unit: 'g', category: 'Baking & Cooking Aids', minThreshold: 50 },
  { item: 'Lemon Yellow Food Color', item_name: 'Lemon Yellow Food Color', qty: 0, quantity: 0, unit: 'g', category: 'Baking & Cooking Aids', minThreshold: 50 },
  { item: 'Orange Red Food Color', item_name: 'Orange Red Food Color', qty: 0, quantity: 0, unit: 'g', category: 'Baking & Cooking Aids', minThreshold: 50 },
  { item: 'Green Food Color', item_name: 'Green Food Color', qty: 0, quantity: 0, unit: 'g', category: 'Baking & Cooking Aids', minThreshold: 50 },
  { item: 'Cumin Powder', item_name: 'Cumin Powder', qty: 0, quantity: 0, unit: 'g', category: 'Spices & Masalas', minThreshold: 200 },
  { item: 'Dry Mango Powder (Amchur)', item_name: 'Dry Mango Powder (Amchur)', qty: 0, quantity: 0, unit: 'g', category: 'Spices & Masalas', minThreshold: 200 },
  { item: 'Whole Cashews', item_name: 'Whole Cashews', qty: 0, quantity: 0, unit: 'kg', category: 'Dry Fruits & Nuts', minThreshold: 1 },
  { item: 'Almonds', item_name: 'Almonds', qty: 0, quantity: 0, unit: 'kg', category: 'Dry Fruits & Nuts', minThreshold: 1 },
  { item: 'Raisins (Kismis)', item_name: 'Raisins (Kismis)', qty: 0, quantity: 0, unit: 'kg', category: 'Dry Fruits & Nuts', minThreshold: 1 },
  { item: 'Chironji / Charoli Nuts', item_name: 'Chironji / Charoli Nuts', qty: 0, quantity: 0, unit: 'g', category: 'Dry Fruits & Nuts', minThreshold: 100 },
  { item: 'Fennel Seeds (Saunf)', item_name: 'Fennel Seeds (Saunf)', qty: 0, quantity: 0, unit: 'kg', category: 'Whole Spices', minThreshold: 1 },
  { item: 'Whole Coriander Seeds', item_name: 'Whole Coriander Seeds', qty: 0, quantity: 0, unit: 'kg', category: 'Whole Spices', minThreshold: 1 },
  { item: 'Niger Seeds (Khurasani)', item_name: 'Niger Seeds (Khurasani)', qty: 0, quantity: 0, unit: 'g', category: 'Whole Spices', minThreshold: 100 },
  { item: 'Baking Powder', item_name: 'Baking Powder', qty: 0, quantity: 0, unit: 'g', category: 'Baking & Cooking Aids', minThreshold: 100 },
  { item: 'Custard Powder', item_name: 'Custard Powder', qty: 0, quantity: 0, unit: 'g', category: 'Baking & Cooking Aids', minThreshold: 200 },
  { item: 'Roasted Gram Dal (Dalia / Chana Phutana)', item_name: 'Roasted Gram Dal (Dalia / Chana Phutana)', qty: 0, quantity: 0, unit: 'kg', category: 'Pulses & Dals', minThreshold: 2 },
  { item: 'Desiccated / Grated Coconut', item_name: 'Desiccated / Grated Coconut', qty: 0, quantity: 0, unit: 'kg', category: 'Dry Fruits & Nuts', minThreshold: 1 },
  { item: 'Vermicelli (Sevai)', item_name: 'Vermicelli (Sevai)', qty: 0, quantity: 0, unit: 'kg', category: 'Packaged & Ready Foods', minThreshold: 2 },
  { item: 'Tadka Whole Red Chillies', item_name: 'Tadka Whole Red Chillies', qty: 0, quantity: 0, unit: 'g', category: 'Whole Spices', minThreshold: 200 },
  { item: 'Black Salt', item_name: 'Black Salt', qty: 0, quantity: 0, unit: 'kg', category: 'Essentials', minThreshold: 1 },
  { item: 'Farsan (Mixture Namkeen)', item_name: 'Farsan (Mixture Namkeen)', qty: 0, quantity: 0, unit: 'kg', category: 'Packaged & Ready Foods', minThreshold: 2 },
  { item: 'Thick Sev', item_name: 'Thick Sev', qty: 0, quantity: 0, unit: 'kg', category: 'Packaged & Ready Foods', minThreshold: 2 },
  { item: 'Nylon / Thin Sev', item_name: 'Nylon / Thin Sev', qty: 0, quantity: 0, unit: 'kg', category: 'Packaged & Ready Foods', minThreshold: 2 },
  { item: 'Noodles', item_name: 'Noodles', qty: 0, quantity: 0, unit: 'kg', category: 'Packaged & Ready Foods', minThreshold: 5 },
  { item: 'Red Chilli (Whole/Sauce)', item_name: 'Red Chilli (Whole/Sauce)', qty: 0, quantity: 0, unit: 'kg', category: 'Condiments & Sauces', minThreshold: 1 },
  { item: 'Green Chilli (Whole/Sauce)', item_name: 'Green Chilli (Whole/Sauce)', qty: 0, quantity: 0, unit: 'kg', category: 'Condiments & Sauces', minThreshold: 1 },
  { item: 'Soya Sauce', item_name: 'Soya Sauce', qty: 0, quantity: 0, unit: 'L', category: 'Condiments & Sauces', minThreshold: 1 },
  { item: 'Pickle', item_name: 'Pickle', qty: 0, quantity: 0, unit: 'kg', category: 'Condiments & Sauces', minThreshold: 5 },
  { item: 'Tasting Powder (MSG / Ajinomoto)', item_name: 'Tasting Powder (MSG / Ajinomoto)', qty: 0, quantity: 0, unit: 'g', category: 'Baking & Cooking Aids', minThreshold: 100 },
  { item: 'Butter', item_name: 'Butter', qty: 0, quantity: 0, unit: 'kg', category: 'Dairy & Fresh', minThreshold: 2 },
  { item: 'Paneer (Cottage Cheese)', item_name: 'Paneer (Cottage Cheese)', qty: 0, quantity: 0, unit: 'kg', category: 'Dairy & Fresh', minThreshold: 5 },
  { item: 'Green Peas (Frozen/Fresh)', item_name: 'Green Peas (Frozen/Fresh)', qty: 0, quantity: 0, unit: 'kg', category: 'Dairy & Fresh', minThreshold: 5 },
  { item: 'Chitale Gulab Jamun Powder Mix', item_name: 'Chitale Gulab Jamun Powder Mix', qty: 0, quantity: 0, unit: 'g', category: 'Baking & Cooking Aids', minThreshold: 500 },
  { item: 'Ragi / Nachni Papad', item_name: 'Ragi / Nachni Papad', qty: 0, quantity: 0, unit: 'kg', category: 'Packaged & Ready Foods', minThreshold: 2 },
  { item: 'Pani Puri Puris', item_name: 'Pani Puri Puris', qty: 0, quantity: 0, unit: 'pcs', category: 'Packaged & Ready Foods', minThreshold: 100 },
  { item: 'Maggi Instant Noodles', item_name: 'Maggi Instant Noodles', qty: 0, quantity: 0, unit: 'pcs', category: 'Packaged & Ready Foods', minThreshold: 24 },
  { item: 'Maggi Magic Cubes / Masala-e-Magic', item_name: 'Maggi Magic Cubes / Masala-e-Magic', qty: 0, quantity: 0, unit: 'pcs', category: 'Spices & Masalas', minThreshold: 20 },
  { item: 'Pasta', item_name: 'Pasta', qty: 0, quantity: 0, unit: 'kg', category: 'Packaged & Ready Foods', minThreshold: 5 },
  { item: 'Pasta Masala Seasoning', item_name: 'Pasta Masala Seasoning', qty: 0, quantity: 0, unit: 'g', category: 'Spices & Masalas', minThreshold: 200 },
  { item: 'Oregano', item_name: 'Oregano', qty: 0, quantity: 0, unit: 'g', category: 'Spices & Masalas', minThreshold: 100 },
  { item: 'Chilli Flakes', item_name: 'Chilli Flakes', qty: 0, quantity: 0, unit: 'g', category: 'Spices & Masalas', minThreshold: 100 },
];
